parent_config: https://raw.githubusercontent.com/sindresorhus/swiftlint-config/main/.swiftlint.yml

disabled_rules:
  - conditional_returns_on_newline
  - identifier_name
  - opening_brace
  - number_separator
  - multiline_arguments
  - implicit_return
excluded:
  - Vendor
  - Tests Apple TV
  - Tests iOS
  - Tests macOS
